### DISCUSSION TITLE
Help with detecting "yes", "no" or "I don't know"

### DISCUSSION THREAD

**Discussion by Lex-Kent** [speechly/speechly#256] [General]
Hi all,

I can honestly say I've never posted so may times to any forum in my entire career!

Now I'm trying to create an application that will detect whether my user meant "yes", "no" or "I don't know" when asked the question "Did I get your name right?" I'm attempting to do this with a lookup. My application page looks like this:

![image](https://user-images.githubusercontent.com/107930534/207334144-99196c2d-56f8-4209-a8a3-cda0e6f36c48.png)

and an extract from my csv file looks like this:

```
nyet, no
of course not, no
on no account, no
over my dead body, no
predictably no you did not, no
predictably no you didn't, no
pretty close but no, no
pretty close but not quite, no
sadly not, no
sadly no, no
seriously no, no
seriously no {$charName} you did not, no
unfortunately not, no
unfortunately no, no
unsurprisingly no, no
what are you deaf, no
you having a giraffe, no
you having a laugh, no
absolutely, yes
actually yeah, yes
actually yep, yes
actually yes, yes
affirmative, yes
assuredly, yes
aye aye, yes
aye, yes
bloody hell yeah you did, yes
```

Once I've uploaded the csv file, I can't actually see what's in it, but I don't see any errors until I try and deploy.

Can anyone offer any guidance as to what I'm doing wrong please?

Thanks so much.

**Comment by teelisyys** [comment]
Hi @Lex-Kent 

You are indeed trying to use the lookups correctly, but unfortunately it seems there is currently an issue in the CSV-import that creates an invalid SAL configuration. Thank you for reporting the issue!

While we are looking into fixing this, it is possible to fix the invalid SAL configuration using our [CLI tool](https://docs.speechly.com/features/cli) by downloading the current config, fixing the configuration file manually and deploying it. (Note that it is not possible to work around this issue using only the Speechly Dashboard.)

The specific issue here is that the `config.yaml` is missing the imports block. For the SAL configuration in the screenshot the imports block should be

~~~
imports:   
  - name: yesNoNameLookupsForSpeechly
    source: yesNoNameLookupsForSpeechly.csv
    field: 1
  - name: yesNoNameLookupsForSpeechly_value
    source: yesNoNameLookupsForSpeechly.csv
    field: 2
~~~

**Reply by Lex-Kent** [reply]
Hi @teelisyys . Thanks so much for your swift response.

What exactly do you mean by "downloading the current config"? Presumably I can download the a `config.yaml`, but how?

EDIT ignore that @teelisyys, I've figured it out!

**Reply by teelisyys** [reply]
Hi! Excellent! 

In case some one else has this issue, here is outline of the needed Speechly CLI commands. Details about the CLI tool can be found from our [documentation](https://docs.speechly.com/features/cli/).

~~~
speechly projects add -apikey <YOUR_API_TOKEN>
speechly download <YOUR_APP_ID> <TARGET_FOLDER>
# edit <TARGET_FOLDER>/config.yaml
speechly deploy <YOUR_APP_ID> <TARGET_FOLDER>
~~~

You can get the api token [following these instructions](https://docs.speechly.com/features/cli/#create-an-api-token).

**Reply by Lex-Kent** [reply]
Hi @teelisyys I'm having no luck with the CLI, I'm just seeing one unhelpful error after another in my terminal.

After editing my `config.yaml` a number of times, it now looks like this:

```
templates: |
  charName = [penny | bridget]
  yes_no_as_spoken = yes
  yes_no_unsure = [yes | no | unsure]

  imports:
    - name: yes_no_as_spoken
      source: yesNoNameLookupsForSpeechly.csv
      field: 1
    - name: yes_no_unsure
      source: yesNoNameLookupsForSpeechly.csv
      field: 2

  entities:
    - name: nameWasCorrect
      type: lookup
      input_items: $yes_no_as_spoken
      output_items: $yes_no_unsure

  *name_correct $yes_no_as_spoken(nameWasCorrect)
intents:
  - name: name_correct
entities:
  - name: nameWasCorrect
    type: string
  - name: yesNoNameLookupsForSpeechly
    type: lookup
    input_items: $yes_no_as_spoken
    output_items: $yes_no_unsure
imports:
  - name: yes_no_as_spoken
    source: yesNoNameLookupsForSpeechly.csv
    field: 1
  - name: yes_no_unsure
    source: yesNoNameLookupsForSpeechly.csv
    field: 2
silence_triggered_segmentation: 100
enable_strict_nlu: true
```

and the latest error I'm seeing is

`ERROR: Variable 'yes_no_as_spoken' is defined twice: on line:1 and line:2. Please leave only one definition.`

but I have no idea if that's referring to my csv file or the yaml.

**Reply by ghost** [reply]
> speechly download <YOUR_APP_ID> <TARGET_FOLDER>

@teelisyys I'm unable to download any <TARGET_FOLDER> with the above command. I tired config and other folder names. All what I get is "Downloading to ... | Reading output directory failed: no such file or directory." I have read and followed the CLI docs and references section as well.

Any suggestions?

**Reply by teelisyys** [reply]
Hi @delegatepattern ! Thank you for using Speechly!

The <TARGET_FOLDER> is the local folder where you want the config files to be downloaded. The folder must exist in your file system for the command to work, and the error suggest that it does not:

~~~
% speechly download $APP_ID foobarbaz
Downloading to [..]/foobarbaz
Reading output directory failed: open [..]/foobarbaz: no such file or directory
% mkdir foobarbaz
% speechly download $APP_ID foobarbaz
Downloading to [..]/foobarbaz
Writing file [..]/foobarbaz/config.yaml (1 bytes)
~~~

**Reply by ghost** [reply]
@teelisyys Thank you so much.

**Comment by teelisyys** [comment]
Hi,

First of all: We have now fixed the issue in the CSV import, so you can now create working lookups from the Dashboard again.

*** 

As for the issue in the posted `config.yaml`, while the line pointers are unfortunately misleading, the issue is indeed that the variable `yes_no_as_spoken` is defined twice. First on the second line of the templates block (`yes_no_as_spoken = yes`). Second definition is in the first import block. The imports feature defines lists outside the SAL configuration, and loads them to variables.

~~~
  - name: yes_no_as_spoken
    source: yesNoNameLookupsForSpeechly.csv
    field: 1
~~~

Please note that you have included imports and entities blocks within the template blocks. This is incorrect and the definitions within the templates block will have no effect. The templates block should have only content with SAL syntax (it maps to the _Training Data_ / _Text adaptation_ in the Dashboard).

To me it looks like the templates block with the rest of the config.yaml as is should be:

~~~
templates: |
  charName = [penny | bridget]
  *name_correct $yes_no_as_spoken(yesNoNameLookupsForSpeechly)
~~~

***

Also please note that the automatic CSV import uses a slightly different naming scheme for the imported variables, so if you recreate the lookups and imports from scratch in the Dashboard, then the _Training data_ in the Dashboard should look like
~~~
charName = [penny | bridget]
*name_correct $yesNoNameLookupsForSpeechly(yesNoNameLookupsForSpeechly)
~~~

**Comment by Lex-Kent** [comment]
Hi @teelisyys 

Since I had no idea what I was doing with the yaml file, I've gone back to simply using the dashboard. However, I still can't get it to deploy!

My dashboard now looks like this:

```
charName = [penny | bridget]

imports:   
  - name: yesNoNameLookupsForSpeechly
    source: yesNoNameLookupsForSpeechly.csv
    field: 1
  - name: yesNoNameLookupsForSpeechly_value
    source: yesNoNameLookupsForSpeechly.csv
    field: 2

*name_correct $yesNoNameLookupsForSpeechly(yesNoNameLookupsForSpeechly)
```

and the error I see when I try to deploy is 

`Template defined on line:3, col:0 might not start with an intent.`

I can't find any examples in your documentation of how to import a csv file into the dashboard without using a `config.yaml`.

And guess what? The documentation page about "[intents and entities](https://docs.speechly.com/features/intents-entities)" tells me nothing about this error.
